language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_API_KEY

install:
  - npm install

script:
  - npm run-script test

